import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { baseURL } from "@/baseUrl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <NextChatSDKBootstrap baseUrl={baseURL} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

function NextChatSDKBootstrap({ baseUrl }: { baseUrl: string }) {
  return (
    <>
      <base href={baseUrl}></base>
      <script>{`window.innerBaseUrl = ${JSON.stringify(baseUrl)}`}</script>
      <script>{`window.__isChatGptApp = typeof window.openai !== "undefined";`}</script>
      <script>
        {"(" +
          (() => {
            const baseUrl = window.innerBaseUrl;

            // Fix postMessage errors by patching postMessage to use the correct origin
            // The OpenAI SDK may try to postMessage to hardcoded origins like 'https://chatgpt.com'
            // but the actual parent origin might be different (e.g., web-sandbox.oaiusercontent.com)
            if (window.self !== window.top && window.top) {
              try {
                let parentOrigin: string | null = null;
                try {
                  if (
                    window.location.ancestorOrigins &&
                    window.location.ancestorOrigins.length > 0
                  ) {
                    parentOrigin = window.location.ancestorOrigins[0];
                  } else if (window.top && window.top !== window.self) {
                    parentOrigin = new URL(window.top.location.href).origin;
                  }
                } catch (e) {
                  // Can't access parent origin due to cross-origin restrictions
                }

                if (parentOrigin) {
                  const originalPostMessage = window.postMessage.bind(window);
                  (window as any).postMessage = function (
                    message: any,
                    targetOrigin: string | WindowPostMessageOptions,
                    transfer?: Transferable[]
                  ) {
                    // If trying to postMessage to a hardcoded ChatGPT origin, use the actual parent origin
                    if (
                      typeof targetOrigin === "string" &&
                      (targetOrigin.includes("chatgpt.com") ||
                        targetOrigin === "*")
                    ) {
                      try {
                        originalPostMessage(message, parentOrigin!, transfer);
                        return;
                      } catch (e) {
                        // If that fails, try with '*'
                        try {
                          originalPostMessage(message, "*", transfer);
                          return;
                        } catch (e2) {
                          // Silently fail if postMessage still fails
                          console.debug(
                            "postMessage failed, likely due to cross-origin restrictions:",
                            e2
                          );
                        }
                      }
                    }
                    // For other cases, use original behavior
                    try {
                      if (typeof targetOrigin === "string") {
                        originalPostMessage(message, targetOrigin, transfer);
                      } else {
                        originalPostMessage(message, targetOrigin);
                      }
                    } catch (e) {
                      console.debug("postMessage failed:", e);
                    }
                  };
                }
              } catch (e) {
                // Silently handle errors accessing parent window (cross-origin restrictions)
                console.debug("Could not patch postMessage:", e);
              }
            }

            // Prevent cookies from being set with invalid domains in iframe context
            // This intercepts cookie setting and ensures cookies use the correct domain
            const originalCookieDescriptor =
              Object.getOwnPropertyDescriptor(Document.prototype, "cookie") ||
              Object.getOwnPropertyDescriptor(HTMLDocument.prototype, "cookie");

            if (originalCookieDescriptor && originalCookieDescriptor.set) {
              const originalCookieSetter = originalCookieDescriptor.set;
              Object.defineProperty(document, "cookie", {
                get: originalCookieDescriptor.get,
                set: function (value: string) {
                  // Skip Cloudflare cookies that cause domain issues in iframes
                  if (value.includes("__cf_bm") || value.includes("_cfuvid")) {
                    // Don't set cookies that will be rejected due to domain restrictions
                    return;
                  }
                  // For other cookies, try to set them normally
                  try {
                    originalCookieSetter.call(this, value);
                  } catch (e) {
                    // Silently ignore cookie setting errors in iframe context
                    const cookieName = value.split(";")[0].split("=")[0];
                    console.debug(
                      "Cookie setting failed (likely due to iframe restrictions):",
                      cookieName
                    );
                  }
                },
                configurable: true,
              });
            }

            const htmlElement = document.documentElement;
            const observer = new MutationObserver((mutations) => {
              mutations.forEach((mutation) => {
                if (
                  mutation.type === "attributes" &&
                  mutation.target === htmlElement
                ) {
                  const attrName = mutation.attributeName;
                  if (attrName && attrName !== "suppresshydrationwarning") {
                    htmlElement.removeAttribute(attrName);
                  }
                }
              });
            });
            observer.observe(htmlElement, {
              attributes: true,
              attributeOldValue: true,
            });

            const originalReplaceState = history.replaceState;
            history.replaceState = (s, unused, url) => {
              const u = new URL(url ?? "", window.location.href);
              const href = u.pathname + u.search + u.hash;
              originalReplaceState.call(history, unused, href);
            };

            const originalPushState = history.pushState;
            history.pushState = (s, unused, url) => {
              const u = new URL(url ?? "", window.location.href);
              const href = u.pathname + u.search + u.hash;
              originalPushState.call(history, unused, href);
            };

            const appOrigin = new URL(baseUrl).origin;
            const isInIframe = window.self !== window.top;

            window.addEventListener(
              "click",
              (e) => {
                const a = (e?.target as HTMLElement)?.closest("a");
                if (!a || !a.href) return;
                const url = new URL(a.href, window.location.href);
                if (
                  url.origin !== window.location.origin &&
                  url.origin != appOrigin
                ) {
                  try {
                    if (window.openai) {
                      window.openai?.openExternal({ href: a.href });
                      e.preventDefault();
                    }
                  } catch {
                    console.warn(
                      "openExternal failed, likely not in OpenAI client"
                    );
                  }
                }
              },
              true
            );

            if (isInIframe && window.location.origin !== appOrigin) {
              const originalFetch = window.fetch;

              window.fetch = (input: URL | RequestInfo, init?: RequestInit) => {
                let url: URL;
                if (typeof input === "string" || input instanceof URL) {
                  url = new URL(input, window.location.href);
                } else {
                  url = new URL(input.url, window.location.href);
                }

                if (url.origin === appOrigin) {
                  if (typeof input === "string" || input instanceof URL) {
                    input = url.toString();
                  } else {
                    input = new Request(url.toString(), input);
                  }

                  return originalFetch.call(window, input, {
                    ...init,
                    mode: "cors",
                  });
                }

                if (url.origin === window.location.origin) {
                  const newUrl = new URL(baseUrl);
                  newUrl.pathname = url.pathname;
                  newUrl.search = url.search;
                  newUrl.hash = url.hash;
                  url = newUrl;

                  if (typeof input === "string" || input instanceof URL) {
                    input = url.toString();
                  } else {
                    input = new Request(url.toString(), input);
                  }

                  return originalFetch.call(window, input, {
                    ...init,
                    mode: "cors",
                  });
                }

                return originalFetch.call(window, input, init);
              };
            }
          }).toString() +
          ")()"}
      </script>
    </>
  );
}
